### ISSUE TITLE
almost got it running ...

### ISSUE THREAD

**Issue by randi120** [sarkonovich/Alexa-Hue#2]
Hi @sarkonovich, 
Thanks for this. I think it provides much needed functionality to the Echo and Hue compatibility. 

Your instructions are great, I was able to follow them and get everything almost up and running. 
I am getting hung up on the last part. 
The basics: lambda, skills, and ngrok are working, app runs but produces errors.
I set up the basic authorization, as well as the application id check. 
I can see the request from Echo being received on the ngrok logs. 
As far as I can tell, Echo is passing the correct info through the lambada and to app.rb (example log below). 
However, it is erroring when trying to execute the request.

Some Info: 
The custom slots of type `LIGHTS` contains `bedroom lights` and various specific lights, eg. `overhead desk light`. 

I can use the debug feature of the hue to directly control the hub from the server via web-browser. 
Example: running  `GET /api/<user_id>/lights` on  `http://<bridge ip address>/debug/clip.html` 
produces 

``` json
{ "1": { "state": <stuff here> , "type": "Extended color light", "name": "Overhead Desk",  <more stuff>}, 
  "2": { "state": <stuff here> , "type": "Extended color light", "name": "Overhead Door", <more stuff> }, 
  "3": { "state": <stuff here> , "type": "Extended color light", "name": "Overhead Other",  <more stuff>}
}
```

and `GET /api/<user_id>groups/`  

``` json
{ "1": { "name": "bedroom lights", 
          "lights": [ "1", "2", "3" ], 
          "type": "LightGroup", 
          "action": <stuff here> 
         }
}
```

However, when it comes down to the `app.rb` I get some weird errors.
When I run the skill for the first time, I don't get any feedback, e.g., no remainder to pair. This is independent of whether I push the link button on the bridge or not (I've tried multiple times).

Here is an example of the types of errors: 
The request:  `Alexa tell house lights to turn the bedroom lights blue`

``` ruby
$ ruby app.rb 
[2016-01-28 22:15:19] INFO  WEBrick 1.3.1
[2016-01-28 22:15:19] INFO  ruby 2.3.0 (2015-12-25) [x86_64-darwin10.0]
== Sinatra (v1.4.7) has taken the stage on 4567 for development with backup from WEBrick
[2016-01-28 22:15:19] INFO  WEBrick::HTTPServer#start: pid=288 port=4567
#<struct brightness=nil, start=nil, stop=nil, saturation=nil, color="blue", time=nil, endsession=nil, string=nil, scene=nil, savescene=nil, lights="bedroom lights", state=nil, schedule=nil, flash=nil>
color blue  bedroom lights  
color blue  bedroom lights  
2016-01-28 22:41:56 - NameError - uninitialized constant Sinatra::Lights::Switch:
    /Alexa-Hue/lights.rb:60:in `block in registered'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
    /usr/local/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
    /usr/local/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
    /usr/local/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
    /usr/local/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
    /usr/local/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
    /usr/local/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
    /usr/local/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/show_exceptions.rb:25:in `call'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `block in call'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1787:in `synchronize'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `call'
    /usr/local/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
    /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
    /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
    /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
127.0.0.1 - - [28/Jan/2016:22:41:56 EST] "POST /lights HTTP/1.1" 500 119401
- -> /lights
127.0.0.1 - - [28/Jan/2016:22:41:58 EST] "POST /lights HTTP/1.1" 200 186
- -> /lights
```

Another one not involving the groups but a single light 
The request:  `Alexa tell house lights to turn the overhead desk light blue`

``` ruby
#<struct brightness=nil, start=nil, stop=nil, saturation=nil, color="blue", time=nil, endsession=nil, string=nil, scene=nil, savescene=nil, lights="overhead desk light", state=nil, schedule=nil, flash=nil>
color blue  overhead desk light  
color blue  overhead desk light  
2016-01-28 23:28:05 - NameError - uninitialized constant Sinatra::Lights::Switch:
    /Alexa-Hue/lights.rb:60:in `block in registered'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
    /usr/local/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
    /usr/local/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
    /usr/local/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
    /usr/local/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
    /usr/local/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
    /usr/local/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
    /usr/local/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/show_exceptions.rb:25:in `call'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `block in call'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1787:in `synchronize'
    /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `call'
    /usr/local/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
    /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
    /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
    /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
127.0.0.1 - - [28/Jan/2016:23:28:05 EST] "POST /lights HTTP/1.1" 500 119401
- -> /lights
127.0.0.1 - - [28/Jan/2016:23:28:07 EST] "POST /lights HTTP/1.1" 200 186
- -> /lights
^C== Sinatra has ended his set (crowd applauds)
[2016-01-28 23:37:19] INFO  going to shutdown ...
[2016-01-28 23:37:19] INFO  WEBrick::HTTPServer#start done.
```

Any ideas as to what could be the problem?

Thanks

**Comment by sarkonovich** [comment]
Hey there! Thanks for letting me know!

Yes. You definitely have it running absolutely correctly. That error is a
bug. I made some changes to the code about a week ago, and I bet I borked
it. Just out of curiosity, did you download this within the last week?

I'll go take a look. It's naming issue...I must have misnamed a module.

I'll let you know when I fix it. Should be soon.

Best,
Steve

**Comment by sarkonovich** [comment]
I'm at work, so can't test, but see if this works. On line 60 of lights.rb
replace:

switch = Switch.new

with

switch = Hue::Switch.new

Best,
Steve

**Comment by sarkonovich** [comment]
Yep...pretty sure that's it. Let me know if it fixed it for you.

Thanks again,

Steve

**Comment by randi120** [comment]
That was quick! Thanks. 
I downloaded it last night, so definitely within the week. 
I am not home right now, so I can't check either.
But It will be the first thing I do when I get there. I'll keep you posted.

Thanks

**Comment by randi120** [comment]
it's alive! 
it works like a charm. I can't believe it was that simple. :)

Gonna tinker with it now.
Thanks!!!

**Comment by sarkonovich** [comment]
Great!

I'm not sure if I updated some of the sample utterances, but I did some
tweaking to that to improve recognition accuracy/variability. I'll see if
the latest version is on github.

Let me know if you run into bugs, or things don't work right. I'm happy to
keep tweaking it.

Best,
Steve

**Comment by randi120** [comment]
Hey, 
So things are pretty much working as desired. I ran into some issues with the scenes but worked through them.

The main thing was with the color loop. I couldn't directly stop them. So I added the utterance 
`ControlLights stop {color loop|Stop} on the {Lights}` 

This is pretty awesome.
Thanks!

**Comment by sarkonovich** [comment]
Hey, that's great!

I keep meaning to add something to the ReadMe about scenes and groups.

The problem with scenes is that every app I know actually stores them on
the bridge as an alphanumeric string, so there's no way to recall them with
your voice. They appear in the app as a name, but on the bridge they are
really "345HJS8SG230BC-DFHE333". For Alexa to get at them, they need to be
stored as something like, "evening."

There's an easy way to do this using hue_switch.rb. But if you found an
easier way, please let me know!

Steve

**Comment by randi120** [comment]
Hey,
Sorry, I meant to get back to you on this.
To set the groups and scenes I went through the debug page from the hub
http://www.developers.meethue.com/documentation/getting-started.
Set the scene by issuing a
POST to  /api/<username>/scenes/<id>
with body:
{"name":"<name>", "lights":["1","2"]}
It was quite simple, and done with a few clicks.
I did the same thing for creating the groups.

The only thing that I can think of is to make the scene setting process
simpler is to switch the search from <id> to <name>.
So that we would tell Alexa a <name> and then scripts (eg. hue_switch.rb)
would do a pull of all scenes and do partial string matching to find proper
name (since most apps tag on extra stuff to the name as well) then get the
<id> and set using it.
There are a few things to work out, including multiple partial matches and
so on, but this might work.

**Comment by sarkonovich** [comment]
Yeah, using the debugger is a good way to go.

You can also save scenes associated with _all_ lights via voice. Just set
up the lights how you'd like, launch the skill, and say, "Save scene as
<example>"
But, it will affect all the lights.

Right now, the program does work the way you suggest --  grabs all the
scenes names (and ids) from the bridge and matches them to the name Alexa
hears. But you're right, it does no fuzzy matching, and that would be good.

One day I'll dive back into the code, make it less of a mess, and fix
stuff. I just keep expecting Amazon+Hue to introduce most of what this does
natively!

Steve

**Comment by randi120** [comment]
Hopefully that will come one day.
But either way, many thanks!
