### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by dennisgove** [sarkonovich/Alexa-Hue#26]
I'm setting up the skill on AWS and when I try to test it I see that a request is hitting my running server (I'm running the docker container on OS X). However, the server is failing to respond with a valid response. Instead I get back to a "500 Internal Server Error" and see the following on the console
```
2016-12-03 16:23:11 - Errno::ECONNRESET - Connection reset by peer:
	/usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/protocol.rb:153:in `read_nonblock'
	/usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/protocol.rb:153:in `rbuf_fill'
	/usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/protocol.rb:122:in `read_all'
	/usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http/response.rb:298:in `block in read_body_0'
	/usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http/response.rb:275:in `inflater'
	/usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http/response.rb:280:in `read_body_0'
	/usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http/response.rb:201:in `read_body'
	/usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http/response.rb:226:in `body'
	/usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http/response.rb:163:in `reading_body'
	/usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:1422:in `transport_request'
	/usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:1384:in `request'
	/usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:1377:in `block in request'
	/usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:853:in `start'
	/usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:1375:in `request'
	/usr/local/rvm/gems/ruby-2.2.4/gems/httparty-0.13.7/lib/httparty/request.rb:117:in `perform'
	/usr/local/rvm/gems/ruby-2.2.4/gems/httparty-0.13.7/lib/httparty.rb:545:in `perform_request'
	/usr/local/rvm/gems/ruby-2.2.4/gems/httparty-0.13.7/lib/httparty.rb:476:in `get'
	/usr/local/rvm/gems/ruby-2.2.4/gems/httparty-0.13.7/lib/httparty.rb:583:in `get'
	/usr/local/www/Alexa-Hue/hue_switch.rb:247:in `authorize_user'
	/usr/local/www/Alexa-Hue/hue_switch.rb:49:in `initialize'
	/usr/local/www/Alexa-Hue/lights.rb:20:in `new'
	/usr/local/www/Alexa-Hue/lights.rb:20:in `block in registered'
	/usr/local/rvm/gems/ruby-2.2.4/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
	/usr/local/rvm/gems/ruby-2.2.4/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
	/usr/local/rvm/gems/ruby-2.2.4/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `[]'
	/usr/local/rvm/gems/ruby-2.2.4/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
	/usr/local/rvm/gems/ruby-2.2.4/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
	/usr/local/rvm/gems/ruby-2.2.4/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
	/usr/local/rvm/gems/ruby-2.2.4/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
	/usr/local/rvm/gems/ruby-2.2.4/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
	/usr/local/rvm/gems/ruby-2.2.4/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
	/usr/local/rvm/gems/ruby-2.2.4/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
	/usr/local/rvm/gems/ruby-2.2.4/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
	/usr/local/rvm/gems/ruby-2.2.4/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
	/usr/local/rvm/gems/ruby-2.2.4/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
	/usr/local/rvm/gems/ruby-2.2.4/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
	/usr/local/rvm/gems/ruby-2.2.4/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
	/usr/local/rvm/gems/ruby-2.2.4/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
	/usr/local/rvm/gems/ruby-2.2.4/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
	/usr/local/rvm/gems/ruby-2.2.4/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
	/usr/local/rvm/gems/ruby-2.2.4/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
	/usr/local/rvm/gems/ruby-2.2.4/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
	/usr/local/rvm/gems/ruby-2.2.4/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
	/usr/local/rvm/gems/ruby-2.2.4/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
	/usr/local/rvm/gems/ruby-2.2.4/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
	/usr/local/rvm/gems/ruby-2.2.4/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/local/rvm/gems/ruby-2.2.4/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/local/rvm/gems/ruby-2.2.4/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/local/rvm/gems/ruby-2.2.4/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/local/rvm/gems/ruby-2.2.4/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/local/rvm/gems/ruby-2.2.4/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
	/usr/local/rvm/gems/ruby-2.2.4/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/usr/local/rvm/gems/ruby-2.2.4/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
	/usr/local/rvm/gems/ruby-2.2.4/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
	/usr/local/rvm/gems/ruby-2.2.4/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `block in call'
	/usr/local/rvm/gems/ruby-2.2.4/gems/sinatra-1.4.7/lib/sinatra/base.rb:1787:in `synchronize'
	/usr/local/rvm/gems/ruby-2.2.4/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `call'
	/usr/local/rvm/gems/ruby-2.2.4/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
	/usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
	/usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
	/usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
172.17.0.3 - - [03/Dec/2016:16:23:11 EST] "POST /lights HTTP/1.1" 500 30
- -> /lights
```

I do have the skill enabled on my Alexa app, but I am not sure if it is correctly linked with my Hue hub. I hit the button on my hub and enabled the skill (within 30 seconds). I'm not quite sure what the issue might be.

The test utterance I'm sending from the AWS Skill test page is "turn on main light" (also tried "Aeneas turn on main light" and "ask Aeneas to turn on the main light" and "alexa ask aeneas to turn on main light". In my Hue hub I have a light called "Main" and in the AWS Skill custom slot type, for LIGHTS I have a light "main light".

**Comment by dennisgove** [comment]
I have also confirmed that speaking to my Echo dot results in a request going to the server and the same 500 error occurring. I suspect it's a failure to connect to the hue hub, but I haven't dug into the code enough yet to be sure.

**Comment by sarkonovich** [comment]
Dennis,

Yeah, it's an authorization failure. The program is trying to register a
new user and it's failing. I've seen this before.
I'm not sure how handy you are with Docker, but the quickest way to fix
this is just to hardcode in your Hue Bridge IP.

In particular, just change line 33 of hue_switch.rb from this:

@ip = HTTParty.get("https://www.meethue.com/api/nupnp").first[
"internalipaddress"] rescue nil

To this:

@ip = [your_bridge_ip]

For example,

@ip = "192.168.1.1"

 The easiest way to do this in Docker is to launch Kitematic, then on the
left hand column highlight the 'docker-alexa-hue' container.
Next, in the middle column, click on 'Exec' to open up a terminal window.
Then using a terminal editor (I think vi is already installed) edit that
line, save the file, and restart the docker container. I *think* that will
work.

**Comment by dennisgove** [comment]
Thanks. I made that change and set the line to `@ip = "192.168.1.5"`. Looking at the code, the way I got the ip from https://www.meethue.com/api/nupnp should've worked just fine.

However, I'm still getting the same error.

I think it's actually a problem with the `@user`. If I'm reading line 29 correctly, this is attempting to get the user from a file called "alexa_hue_user" (but the indentation and `begin` on line 30 is concerning me that I don't know enough ruby). I don't see any file called "alexa_hue_user" of anything that File.read(...) would be able to find called "alexa_hue_user"

So, all the places where it makes a call to http://#{@ip}/api/#{@user} seem to be failing.

**Comment by sarkonovich** [comment]
Sounds plausible....it's been so long since I've looked at this code. Let
me check it out and get back to you!

Steve

**Comment by dennisgove** [comment]
Following the instructions on https://developers.meethue.com/documentation/getting-started I should be able to create a user. Trying now.

**Comment by dennisgove** [comment]
Was able to create a user and going to http://192.168.1.5/api/y1OnLRDGBM5PkI10U7sesyrUiwnOeYcdvj1ROaFA/config returns the following content

```
{"name":"Philips hue","zigbeechannel":11,"bridgeid":"001788FFFE2237F3","mac":"00:17:88:22:37:f3","dhcp":true,"ipaddress":"192.168.1.5","netmask":"255.255.255.0","gateway":"192.168.1.1","proxyaddress":"none","proxyport":0,"UTC":"2016-12-03T23:28:51","localtime":"2016-12-03T18:28:51","timezone":"America/New_York","modelid":"BSB002","swversion":"01036562","apiversion":"1.15.0","swupdate":{"updatestate":2,"checkforupdate":false,"devicetypes":{"bridge":false,"lights":["3","4","5"],"sensors":[]},"url":"","text":"ZGB_100B_010C - 11.14","notify":false},"linkbutton":false,"portalservices":true,"portalconnection":"connected","portalstate":{"signedon":true,"incoming":true,"outgoing":true,"communication":"disconnected"},"factorynew":false,"replacesbridgeid":null,"backup":{"status":"idle","errorcode":0},"whitelist":{"24f7994b5a2354871e592c9d1d498849":{"last use date":"2016-12-03T23:24:22","create date":"2016-12-03T00:51:22","name":"Hue 2#Samsung SM-G930V"},"haR1trwCW4OWxgvnvVW15v7e1ychENTJxXiJkJV8":{"last use date":"2016-12-03T23:24:22","create date":"2016-12-03T01:07:08","name":"Echo"},"IM6WBNPeDNS1pZn7u9TMpYSD8Irb0X5rZVNuaSc8":{"last use date":"2016-12-03T23:24:22","create date":"2016-12-03T02:46:14","name":"all 4 hue#SM-G930V"},"4PhhCY9hvqR0uhlpbPmp7mCBPpOhKkV7AEPcD0vn":{"last use date":"2016-12-03T16:39:28","create date":"2016-12-03T16:39:28","name":"hue-alexa-smarthome-skill-v1"},"y1OnLRDGBM5PkI10U7sesyrUiwnOeYcdvj1ROaFA":{"last use date":"2016-12-03T23:28:51","create date":"2016-12-03T23:22:50","name":"alexa_aeneas#alexa dennis"}}}
```

It's weird cause the line it's failing on (with a CONNECTION RESET error) is making a call to that url. I've confirmed I can hit that from browser, curl on my mac, and curl from within the container. All return the same content. I don't know why the line is giving a connection reset error.

**Comment by sarkonovich** [comment]
Dennis,

Hmm. Well, you could also just hardcode in your username on line 29 using
any of the whitelisted users from the JSON you just posted.

So

@user="haR1trwCW4OWxgvnvVW15v7e1ychENTJxXiJkJV8"

instead of the File.read line.

It looks like the the connection refused is coming from line 247 of
hue_switch....

Steve

**Comment by dennisgove** [comment]
I tried that - hardcoding @user. 

It appears that all http requests are failing. I added a line to do a `HTTParty.get("www.google.com")` and it failed too (though with a CONNECTION REFUSED instead of RESET).

**Comment by dennisgove** [comment]
I think this is a connectivity issue on my docker daemon...

I created a simple ruby app on the container doing this
```
def go()
  @res = HTTParty.get("http://192.168.1.5/api/y1OnLRDGBM5PkI10U7sesyrUiwnOeYcdvj1ROaFA/scenes")
end

go()
```

and when run got an error
```
sh-4.3# /bin/bash -l -c "ruby test.rb"
/usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:879:in `initialize': Network is unreachable - connect(2) for "192.168.1.5" port 80 (Errno::ENETUNREACH)
	from /usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:879:in `open'
	from /usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'
	from /usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/timeout.rb:73:in `timeout'
	from /usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:878:in `connect'
	from /usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
	from /usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:852:in `start'
	from /usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:1375:in `request'
	from /usr/local/rvm/gems/ruby-2.2.4/gems/httparty-0.13.7/lib/httparty/request.rb:117:in `perform'
	from /usr/local/rvm/gems/ruby-2.2.4/gems/httparty-0.13.7/lib/httparty.rb:545:in `perform_request'
	from /usr/local/rvm/gems/ruby-2.2.4/gems/httparty-0.13.7/lib/httparty.rb:476:in `get'
	from /usr/local/rvm/gems/ruby-2.2.4/gems/httparty-0.13.7/lib/httparty.rb:583:in `get'
	from test.rb:14:in `go'
	from test.rb:17:in `<main>'
```

**Comment by dennisgove** [comment]
No, I take that back. This works fine `sh-4.3# /bin/bash -l -c "curl www.google.com"`

**Comment by sarkonovich** [comment]
Away from computer, but yes, I think it's a docker issue....

**Comment by dennisgove** [comment]
Thank you so much for your help. It turns out the whole issue was related to using an less-than-up-to-date version of virtualbox. Updating to virtualbox 5.1.10 https://www.virtualbox.org/ticket/16084 made this work out of the box.

Great work, I love it already!
